# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171215_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('content_type', models.SmallIntegerField(default=0)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('sort_value', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-modify_time'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='menu_json',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Product'),
        ),
    ]
