# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-18 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171218_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='content',
            name='name',
        ),
        migrations.RemoveField(
            model_name='content',
            name='sort_value',
        ),
    ]
